# https://commitlint.js.org/reference/configuration.html

# Resolve and load @commitlint/config-conventional from node_modules
# https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional
extends: "@commitlint/config-conventional"

# Resolve and load conventional-changelog-atom from node_modules
parserPreset: "conventional-changelog-atom"

# Resolve and load @commitlint/format from node_modules
formatter: "@commitlint/format"

# Custom URL to show upon failure
helpUrl: "https://github.com/conventional-changelog/commitlint/#what-is-commitlint"

# Any rules defined here will override rules from @commitlint/config-conventional
rules:
  # Levels
  # 0: disable the rule
  # 1: considered as a warning
  # 2: considered as an error

  # Applicable always|never: never inverts the rule
  # Value: value to use for this rule

  # Body
  body-case: [2, always, lower-case]
  body-empty: [0, never]
  body-full-stop: [0, never, .]
  body-leading-blank: [1, always]  # conventional-commits
  body-max-length: [2, always, 1000]
  body-max-line-length: [2, always, 72]  # conventional-commits (default: 100)
  body-min-length: [2, always, 0]

  # Footer
  footer-empty: [0, never]
  footer-leading-blank: [1, always]  # conventional-commits
  footer-max-length: [2, always, 1000]
  footer-max-line-length: [2, always, 72]  # conventional-commits (default: 100)
  footer-min-length: [2, always, 0]

  # Header
  header-case: [2, always, lower-case]
  header-full-stop: [2, never, .]
  header-max-length: [2, always, 50]  # conventional-commits (default: 100)
  header-min-length: [2, always, 0]
  header-trim: [2, always]

  # Scope
  scope-case: [2, always, lower-case]
  scope-empty: [0, never]
  scope-enum: [0, always, []]
  scope-max-length: [2, always, 50]
  scope-min-length: [2, always, 0]

  # Subject
  subject-case:  # conventional-commits
    [2, never, ["sentence-case", "start-case", "pascal-case", "upper-case"]]
  subject-empty: [2, never]  # conventional-commits
  subject-exclamation-mark: [0, never]
  subject-full-stop: [2, never, "."]  # conventional-commits
  subject-max-length: [2, always, 50]
  subject-min-length: [2, always, 0]

  # Type
  type-case: [2, always, lower-case]  # conventional-commits
  type-empty: [2, never]  # conventional-commits
  type-enum:  # conventional-commits
    [
      2,
      always,
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ]
  type-max-length: [2, always, 10]
  type-min-length: [2, always, 0]

  # Other
  # breaking-change-exclamation-mark: [0, always]
  references-empty: [0, never]
  signed-off-by: [0, always, "signed-off-by:"]
  trailer-exists: [0, always, "signed-off-by:"]
